/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutApp: typeof import('./src/components/about-app.vue')['default']
    AppVersions: typeof import('./src/components/app-versions.vue')['default']
    DiffEditor: typeof import('./src/components/diff-editor.vue')['default']
    DropDown: typeof import('./src/components/drop-down.vue')['default']
    JsonEditor: typeof import('./src/components/json-editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('./src/components/tag.vue')['default']
    TinyButton: typeof import('@opentiny/vue-button')['default']
    TinyContainer: typeof import('@opentiny/vue-container')['default']
    TinyDialogBox: typeof import('@opentiny/vue-dialog-box')['default']
    TinyDropdown: typeof import('@opentiny/vue-dropdown')['default']
    TinyDropdownItem: typeof import('@opentiny/vue-dropdown-item')['default']
    TinyDropdownMenu: typeof import('@opentiny/vue-dropdown-menu')['default']
    TinyScrollText: typeof import('@opentiny/vue-scroll-text')['default']
    TinyTreeMenu: typeof import('@opentiny/vue-tree-menu')['default']
    WinBtn: typeof import('./src/components/win-btn.vue')['default']
  }
}
