/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutApp: typeof import('./src/components/about-app.vue')['default']
    AppVersions: typeof import('./src/components/app-versions.vue')['default']
    DiffEditor: typeof import('./src/components/diff-editor.vue')['default']
    DropDown: typeof import('./src/components/drop-down.vue')['default']
    JsonEditor: typeof import('./src/components/json-editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyButton: typeof import('@opentiny/vue')['Button']
    TinyCollapse: typeof import('@opentiny/vue')['Collapse']
    TinyCollapseItem: typeof import('@opentiny/vue')['CollapseItem']
    TinyContainer: typeof import('@opentiny/vue')['Container']
    TinyDialogBox: typeof import('@opentiny/vue')['DialogBox']
    TinyDropdown: typeof import('@opentiny/vue')['Dropdown']
    TinyDropdownItem: typeof import('@opentiny/vue')['DropdownItem']
    TinyDropdownMenu: typeof import('@opentiny/vue')['DropdownMenu']
    TinyForm: typeof import('@opentiny/vue')['Form']
    TinyFormItem: typeof import('@opentiny/vue')['FormItem']
    TinyInput: typeof import('@opentiny/vue')['Input']
    TinyScrollText: typeof import('@opentiny/vue')['ScrollText']
    TinySwitch: typeof import('@opentiny/vue')['Switch']
    TinyTabItem: typeof import('@opentiny/vue')['TabItem']
    TinyTabs: typeof import('@opentiny/vue')['Tabs']
    TinyTreeMenu: typeof import('@opentiny/vue')['TreeMenu']
    WinBtn: typeof import('./src/components/win-btn.vue')['default']
  }
}
